<Widgets>:
    Label:
        text: "HMC DNA Printing Station"
        size_hint: 0.6, 0.2
        pos: 330, 350

    Button:
        text: "Submit an image here!"
        background_color: 0.5, 0.8, 0.6, 1
        size: 180, 50
        pos: 290, 300 
        on_release: root.btn()

<P>:
    id: my_widget
    FileChooserListView:
        id: filechooser
        on_selection: my_widget.selected(filechooser.selection)
    Image:
        id: image
        source: "/Users/apple/Desktop/DNAPrintingPipeline/DNAPrinting.png"

<P2>:
    id: my_widget2
    Label:
        text: "Further dit your gel!"
        background_color: 0.5, 0.8, 0.6, 1
        size: 200, 50
        pos: 300, 500

    Image:
        id: image
        source: ""
        pos: 320, 300 
